// This file is auto-generated by scripts/emit-version.js
export const sha = 'abe31c3';
export const buildTime = '2026-08-11T10:15:08.130Z';
export const version = 'dev';

export default { sha, buildTime, version };
