// This file is auto-generated by scripts/emit-version.js
export const sha = 'abe31c3';
export const buildTime = '2026-07-28T11:38:10.545Z';
export const version = 'dev';

export default { sha, buildTime, version };
